language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - extra-android-m2repository
  - android-25
jdk:
- oraclejdk8
notifications:
  email: false
licenses:
- android-sdk-license-.+
- android-sdk-license-c81a61d9
sudo: required
script: ./gradlew testDebugUnitTest assemble
cache:
  directories:
  - "$HOME/.gradle"